### ISSUE TITLE
[image_flip] fix image flip to support ROS coordinate system convention

### ISSUE THREAD

**Issue by floweisshardt** [ipa320/cob_perception_common#84]
we found out that we're currently not conform with the ROS coordinate system convention. see https://github.com/ipa320/cob_robots/issues/669. Thus the current implementation of the image_flip node is not correct.
- we should fix image_flip to be aligned with http://www.ros.org/reps/rep-0103.html
- and fix the (wrong) Asus camera systems see https://github.com/ipa320/cob_robots/issues/669

**Comment by fmessmer** [comment]
I don't think it is a problem of image_flip...for `cob4-12` the calibration_default parameters were not correct for the zr300 cameras...I fixed this in unity-robotics/unity-robots#8...then, I can use image flip in mode `1` with the angle set to `0` no matter what the camera orientation is....

@ipa-fmw 
please re-open if you think otherwise...
